---
title: "Gradient plots"
author: "Justin Tiano"
date: '2023-06-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load data

```{r}
load("Grad_new.rda")
GradInfo = df
```

## Selecting columns and merging

```{r}

fulldfsel <- fulldata[,c("article_id", 
                         "article_type_id", 
                         "Location", 
                         "Habitat.type_harmonized", 
                         "Seasonality_harmonized",
                         "Trawling.gear.type_harmonized",
                         "Water.depth..m.",
                         "Sample.core.depth.slice",
                         "Response.variable",
                         "Harmonized_study.type",
                         "Latitude_study",
                         "Longitude_study")]

gradlat <- c(rep(45.68967034, 4) , #1
             rep(56.636, 4)      , #10
             rep(56.95885857, 2) , #13
             rep(38.00789665, 4) , #28
             rep(54.2175, 3)     , #38
             rep(-42, 9)         , #41
             rep(54.23166667, 10), #49
             rep(54.27516197, 9) , #53
             rep(40.6, 5)        , #59
             rep(-30.5, 2)       , #89
             rep(51.783295, 5)   , #136
             rep(56.7, 2)        , #152
             rep(57.8333, 3)     , #183
             rep(22.38518644, 2)) #3

gradlon <- c(rep(-1.683045313,4)  ,
             rep(9.0, 4)          ,
             rep(11.41001333, 2)  ,
             rep(-3.9, 3)         ,
             rep(-9.1547815, 4)   ,
             rep(-175, 9)         ,
             rep(-3.878333333, 10),
             rep(-3.872626026, 9) ,
             rep(0.98, 5)         ,
             rep(15, 2)           ,
             rep(1.8196, 5)       ,
             rep(-153.8, 2)       ,
             rep(-5.6733, 3)      ,
             rep(114.1896949, 2))

GradInfo$Latitude_study <- gradlat
GradInfo$Longitude_study <- gradlon
GradInfo$Harmonized_study_type <- "Gradient"

gradsel <- GradInfo[,c("article_id", 
                       "study", 
                       "Location", 
                       "Habitat.type", 
                       "Seasonality", 
                       "gear.type", 
                       "Water.depth", 
                       "Sample.core.depth.slice", 
                       "Response.variable",
                       "Harmonized_study_type",
                       "Latitude_study",
                       "Longitude_study")]
colnames(gradsel) <- colnames(fulldfsel)

gradsel$Habitat.type_harmonized <- ifelse(gradsel$Habitat.type_harmonized == "Shallow sandy", "Sand", ifelse(gradsel$Habitat.type_harmonized == "Shallow sandy, low tidal disturbance", "Sand", "Mud"))

gradsel$Seasonality_harmonized[gradsel$Seasonality_harmonized == ""] <- "Summer" 
gradsel$Seasonality_harmonized[gradsel$Seasonality_harmonized == "Summer, rainy season, upwelling"] <- "Summer" 
gradsel$Seasonality_harmonized[gradsel$Seasonality_harmonized == "temperate latitude, seasonal, rough seas mentioned in text"] <- "Summer" 

gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "otter trawl"] <- "Otter Trawl"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "Mussel dredge"] <- "Dredging"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "scallop dredge"] <- "Dredging"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "Scallop"] <- "Dredging"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "mixed fishing gears"] <- "Mixed"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "otter trawl beam trawl"] <- "Otter Trawl"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "Lobster"] <- "Local gear net"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == ""] <- "Otter Trawl"
gradsel$Trawling.gear.type_harmonized[gradsel$Trawling.gear.type_harmonized == "Otter trawl"] <- "Otter Trawl"

gradsel$Response.variable[gradsel$Response.variable == "Silt  "] <- "Silt"

gradsel$Sample.core.depth.slice[gradsel$Sample.core.depth.slice == "surface sediment from Van Veen Grabs"] <- "surface sediment"
gradsel$Sample.core.depth.slice[gradsel$Sample.core.depth.slice == "0"] <- "surface sediment"
gradsel$Sample.core.depth.slice[gradsel$Sample.core.depth.slice == ""] <- "surface sediment"

datall <- rbind(fulldfsel, gradsel)

```

```{r}

# Group OM (LOI) with TOC content.
datall$Response.variable[datall$Response.variable == "OM (LOI)"] <- "TOC"

vars <- sort(table(datall$Response.variable), decreasing = TRUE)
sel  <- names(vars)[c(1:12, 14, 15, 18, 19, 20, 21, 22, 26, 28)]
vars <- vars[sel]

tab <- table(datall$Sample.core.depth.slice, datall$Response.variable)
tab <- tab[,names(vars)]

datall$depths <- datall$Sample.core.depth.slice
datall$depths[datall$depths %in% c("0-0.5", "0-1", "0-2", "0-2.5", "0.5-1", "1-1.5", "1-2", "1.5-2", "surface sediment")]   = "Surface" # 0-2
datall$depths[datall$depths %in% c("0-3", "0-4", "0-5", "0-5.5", "1-3", "2-2.5", "2-3", "2-4", "2.5-3", "3-3.5", "3-4", "3-5", "3.5-4", "", "4-4.5", "4-5", "4.5-5")]   = "Subsurface"              # 2-5
datall$depths[datall$depths %in% c("4-6", "4-8", "5-10", "5-6", "5-7", "6-10", "6-7", "7-10", "7-8", "7-9", "8-9", "9-10")]   = "Deep"                    # 5-10
datall$depths[datall$depths %in% c("10-11", "10-12", "10-15", "11-12", "12-13", "13-14", "14-15", "15-16", "15-20", "16-17", "17-18", "18-19", "19-20", "20-21", "21-22", "22-23", "23-24", "24-25", "25-26", "26-27", "27-28", "28-29", "29-30", "30-31", "31-32", "32-33", "33-34", "34-35", "35-36", "36-37", "37-38", "38-39", "39-40", "40-41", "41-42", "42-43")]   = "Very deep"  # > 10
datall$depths[datall$depths %in% c("0-10", "0-30", "Full core", "Grab sample", "in-situ incubations", "on-board incubations")]   = "Full sample"

datall$depths <- factor(datall$depths, levels = c("Surface", "Subsurface", "Deep", "Very deep", "Full sample"))

dftoplot <- data.frame(datall)
dftoplot <- subset(dftoplot, dftoplot$Response.variable %in% names(vars))
dftoplot$Seasonality_harmonized <- factor(dftoplot$Seasonality_harmonized, levels = c("Spring","Summer", "Autumn", "Winter", "Wet", "Dry", "Yearly"))

dftoplot$Water.depth..m. <- as.numeric(dftoplot$Water.depth..m.)
dftoplot$article_type_id <- as.factor(dftoplot$article_type_id)

# Make a dataframe with unique combinations of variables.
comz <- datall %>% distinct(datall$Seasonality_harmonized, datall$article_type_id, datall$Harmonized_study.type, datall$Habitat.type_harmonized, datall$Trawling.gear.type_harmonized, datall$Water.depth..m.)
names(comz) <- c("Season", "ArticleID", "Studytype", "Habitat", "Gear", "Depth")
comz$Season <- factor(comz$Season, levels = c("Spring","Summer", "Autumn", "Winter", "Wet", "Dry", "Yearly"))

season <- datall %>% distinct(datall$Seasonality_harmonized, datall$article_type_id)
season$`datall$Seasonality_harmonized` <- factor(season$`datall$Seasonality_harmonized`, levels = c("Spring","Summer", "Autumn", "Winter", "Wet", "Dry", "Yearly"))

habitat <- datall %>% distinct(datall$Habitat.type_harmonized, datall$article_type_id)
gear <- datall %>% distinct(datall$Trawling.gear.type_harmonized, datall$article_type_id)
depth <- datall %>% distinct(datall$Water.depth..m., datall$article_type_id)
slice <- datall %>% distinct(datall$depths, datall$article_type_id)
slice$`datall$depths` <- factor(slice$`datall$depths`, levels = c("Surface","Subsurface","Deep","Very deep","Full sample"))
studytype <- datall %>% distinct(datall$Harmonized_study.type, datall$article_type_id)

```

## Plot

```{r}

# World
# Create world map
world_map <- map_data("world")

# Plot the world map with points
world <- ggplot() +
  geom_polygon(data = world_map, aes(x = long, y = lat, group = group), fill = "lightgray", color = "black") +
  geom_point(data = datall, aes(x = Longitude_study, y = Latitude_study), color = "orange", size = 2.5) +
  labs(title = "A  Study locations", x = "Longitude", y = "Latitude") + 
  theme_classic()

#### Season, Sediment type, Gear type
#### All variables together
bar_width <- 0.8

## Season
seasonplot <- ggplot(data = season, aes(x = `datall$Seasonality_harmonized`)) + 
              geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
              #geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
              #ylim(0, 30) +
              theme_classic() + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
              #theme(plot.title = element_text(hjust = 0.5)) + 
              labs(title="B  Seasonality", y = "Times included in study design", x = " ")

## Sediment type
sedimentplot <- ggplot(data = habitat, aes(x = habitat$`datall$Habitat.type_harmonized`)) + 
                geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
                # geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
                theme_classic() + 
                # ylim(0, 45) +
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                #theme(plot.title = element_text(hjust = 0.5)) + 
                labs(title="C  Sediment type", y = "", x = " ")

## Gear plot
gearplot <- ggplot(data = gear, aes(x = gear[,1])) + 
            geom_bar( width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
            # geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
            theme_classic() +
            #ylim(0, 44) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            #theme(plot.title = element_text(hjust = 0.5)) + 
            labs(title="D  Gear type", y = "", x = " ")

# Combine the plots using patchwork
combined_plots <- seasonplot + sedimentplot + gearplot
design <- "11233
           11233
"
# Set the heights of the plots to be equal
combined_plots <- combined_plots +
  plot_layout(guides = "collect", heights = c(1, 1, 1), design=design)

# Display the combined plots
combined_plots
ggsave("../figures/final/meta_info_a.png", units = "in", height = 6, width = 12)


## Season
seasonplot <- ggplot(data = season, aes(x = season[,1])) + 
              geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
              #geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
              theme_classic() + 
              #ylim(0, 30) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
              #theme(plot.title = element_text(hjust = 0.5)) + 
              labs(title="D  Seasonality", y = "", x = " ")

## Waterdepth type
depthplot <- ggplot(data = depth, aes(x = as.numeric(depth[,1]))) + 
              geom_histogram(position = "dodge", fill = "lightgrey", bins = 30) +
           #   geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
              theme_classic() + 
           #   ylim(0, 42) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = round(seq(0, max(comz$Depth), by = 50))) +
              #theme(plot.title = element_text(hjust = 0.5)) + 
              labs(title="B  Water depth", y = "Times included in study design", x = " ")

## Slice depth
## Sediment type
sliceplot <- ggplot(data = slice, aes(x = slice[,1])) + 
              geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
              #geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
              theme_classic() + 
              #ylim(0, 30) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
              #theme(plot.title = element_text(hjust = 0.5)) + 
              labs(title="D  Depth strata", y = "", x = " ")

## Studytype
studyplot <- ggplot(data = studytype, aes(x = studytype[,1])) + 
              geom_bar( width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
              #geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
              theme_classic() +
              #ylim(0, 40) +
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              #theme(plot.title = element_text(hjust = 0.5)) + 
              labs(title="C  Study type", y = "", x = " ")

# Combine the plots using patchwork
combined_plots_2 <- seasonplot + studyplot + depthplot + world
design <- "4444444444444
           4444444444444
           4444444444444
           4444444444444
           3333332211111
           3333332211111
"

# Set the heights of the plots to be equal
combined_plots_2 <- combined_plots_2 +
  plot_layout(guides = "collect", design=design)

# Display the combined plots
combined_plots_2
ggsave("~/GitHub/Metastudy2/figures/final/meta_new.png", units = "in", height = 10, width = 12)


# Combine the plots using patchwork
combined_plots_3 <- seasonplot + studyplot + sliceplot + world
design <- "4444444444444
           4444444444444
           4444444444444
           4444444444444
           1111122333333
           1111122333333
"

# Set the heights of the plots to be equal
combined_plots_3 <- combined_plots_3 +
  plot_layout(guides = "collect", design=design)

# Display the combined plots
combined_plots_3
ggsave("../figures/final/meta_info_alt2.png", units = "in", height = 10, width = 12)


# Make a dataframe with unique combinations of variables.
d <- datall$Sample.core.depth.slice
  
datall$samplestrat <- ifelse(d == "Full core", "Full core", ifelse(d == "surface sediment", "Surface sediment", ifelse(d == "in-situ incubations" | d == "on-board incubations", "Core incubation", ifelse(d == "Grab sample", "Grab sample", "Core sections"))))
comz2 <- datall %>% distinct(datall$article_type_id, datall$samplestrat)
names(comz2) <- c("ArticleID", "Samplestyle")
comz2$Samplestyle <- factor(comz2$Samplestyle, levels = c("Core sections", "Full core", "Grab sample", "Surface sediment", "Core incubation"))


stratplot <- ggplot(data = comz2, aes(x = Samplestyle)) + 
             geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgray") +
             #geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
             theme_classic() + 
             #ylim(0, 37) +
             theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
             #theme(plot.title = element_text(hjust = 0.5)) + 
             labs(title= "A  Sampling method", y = "No. occurrences", x = " ")


## Sediment type
sedimentplot <- ggplot(data = habitat, aes(x = habitat$`datall$Habitat.type_harmonized`)) + 
                geom_bar(width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
                # geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
                theme_classic() + 
                # ylim(0, 45) +
                theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
                #theme(plot.title = element_text(hjust = 0.5)) + 
                labs(title="B  Sediment type", y = "", x = " ")

## Gear plot
gearplot <- ggplot(data = gear, aes(x = gear[,1])) + 
            geom_bar( width = bar_width, position = position_dodge(width = 1), fill = "lightgrey") +
            # geom_text(stat='count', aes(label= after_stat(count)), vjust=-1) + 
            theme_classic() +
            #ylim(0, 44) +
            theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
            #theme(plot.title = element_text(hjust = 0.5)) + 
            labs(title="C  Gear type", y = "", x = " ")

# Combine the plots using patchwork
combined_plots <- stratplot + sedimentplot + gearplot
design <- "11233
           11233
"
# Set the heights of the plots to be equal
combined_plots <- combined_plots +
  plot_layout(guides = "collect", heights = c(1, 1, 1), design=design)

# Display the combined plots
combined_plots
ggsave("~/GitHub/Metastudy2/figures/final/meta_info_sampleinfo_new.png", units = "in", height = 6, width = 12)


ggsave("../figures/final/meta_info_sampleinfo.png", units = "in", height = 4, width = 4)
```














```{r}
par(mar = c(4,5,2,4))
plot(NA, xlim = c(-1,1), ylim = c(0,5), ylab = "", axes = F, xlab = "Fishers Z", main = "Fuckin Gradients! (n = 29, I guess)")
boxplot(df$r[df$Response.variable=="TN"],
        df$r[df$Response.variable=="OM (LOI)"],
        df$r[df$Response.variable=="Chl-a"], 
        df$r[df$Response.variable=="TOC"], 
        boxlwd = 2, whisklty=1, whisklwd=2, staplewex=0,lwd = 2, boxwex = 0.75,
        outline = TRUE, ylim = c(-1,1),
        horizontal = TRUE, add = TRUE
        )
abline(v = 0, lwd = 2)
axis(2, at = 4:1, labels = c("TOC", "Chl-a", "OM (LOI)", "TN"), las = 1)
axis(4, at = 4:1, labels = c("n=13", "n=4", "n=9", "n=3"), las = 1)
```