---
title: "Add standard deviations"
author: "Emil De Borger"
date: "01/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
```

# Intro

We add missing standard deviations 

```{r}

df <- read_excel("../dataset/trawling_meta-analysis_grouped17_10_2022.xlsx")
df <- as.data.frame(df)
colnames(df) <- make.names(colnames(df), unique=TRUE)
# colnames(df)[1] = "article_id"
# articles = df[!duplicated(df$article_id), c(1:10)] # Get Articles
# rownames(articles) = 1:nrow(articles)

# corrections
df$"Study.type"[df$article_id==23]="Before After"
df[,c(6, 44, 49, 54)] <- abs(df[,c(6, 44, 49, 54)]) # make all SD positive.

# Make new columns for effect size calculations
df$response1=NA
df$SD1=NA
df$n1=NA

df$response2=NA
df$SD2=NA
df$n2=NA

```

## Fill in missing sd

```{r}

#### Adding in missing SD's.
## Fill in sd function.
# make a not in function for later by negating %in%. !%in% does not work.

`%notin%` <- Negate(`%in%`) 

# Function is missSD and requires columns of the specific treatment to be filled in.
# I don't think i can use all treatments together to calculate missing sd.

missSD <- function(dff, mean, sd, nc) {
  tofill <- which(is.na(dff[,sd]) & !is.na(dff[,mean])) # Rows where I set sd to 9999 (mean reported but no sd).
    for(i in tofill){
        if(dff[i,nc] == 1){             # If n = 1 then the sd is just 0.
          dff[i, sd] <- 0        
        } else{
          var      <- dff$`Response.variable`[i] # select variable of row.  
          st       <- dff$`Harmonized_study.type`[i] # select study type of row.
          
          # Use variable and study type to take a subset of similar measurements of which sd can be computed.
          subset   <- subset(dff[,c(1,14,mean, sd, nc)], dff$`Response.variable` == var & dff$`Harmonized_study.type` == st)
          
          # summed means -> sum all means of which an sd is known in subset.
          smean <- sum(na.omit(subset[rownames(subset) %notin% tofill, 3]))
          
          # summed sd -> sum all known sds in subset.
          ssd   <- sum(na.omit(subset[rownames(subset) %notin% tofill, 4]))
          
          # Calc the new sd with formula from book and replace sd.
          newsd     <- dff[i, mean] * ssd/smean
          dff[i, sd] <- abs(newsd)
        }
    }
  return(dff[,sd])
}

newdf <- df
newdf[,6]  <- missSD(dff = df, mean = 3, sd = 6, nc = 7)     # After control
newdf[,44] <- missSD(dff = df, mean = 41, sd = 44, nc = 45)  # After Impact
newdf[,49] <- missSD(dff = df, mean = 46, sd = 49, nc = 50)  # Before impact
newdf[,54] <- missSD(dff = df, mean = 51, sd = 54, nc = 55)  # Before control

save(newdf, file = "../dataset/dataset.rdata")

```