---
title: "To do"
author: "Emil De Borger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# To do for final version

- Check whether excess LnRR values are result of:
  - adding 0.001 to responses. OK
    --> These are for Sand (a few), excess Pb and Th (a few), and gravel (majority). We're not using gravel and the excess Pb anyways, so only checking sand.
    --> I will just remove all these. 
  - sth. wrong when inputting the data in the dataset. OK --> No more obvious errors. ==> Check LINE 1727 TN ==> No error, it looks like this.

- Meta-modelling
  - Double check if meta-models mean what I think they mean. 
  - Do work with HSeason, HSedtype. OK
  - Make models including primary productivity. OK

- Additional plots
  - Amount of data for each season, trawling gear,... OK
  - Plot of experimental vs. observational,... OK

Plots:
- Change order of y-axis labels OK
- Add colors for sediment type in cloud plots OK
- p-Values not necessary in forest plots OK
- Add colours to forest plot corresponding to variable type or split plots. OK
- Cut-off for forest plots is variables with at least three studies. OK
- Add a "0" line to meta-model plots. OK
